### ISSUE TITLE
mynotes stops working

### ISSUE THREAD

**Issue by sispus** [j4321/MyNotes#26]
Hi,
When I try to start mynotes in terminal in Manjaro XFCE, it says:

$ mynotes
Traceback (most recent call last):
  File "/usr/sbin/mynotes", line 31, in <module>
    from mynoteslib.constants import save_config, PIDFILE
  File "/usr/lib/python3.7/site-packages/mynoteslib/constants.py", line 53, in <module>
    import ewmh
ModuleNotFoundError: No module named 'ewmh'

How can I fix it?

**Comment by j4321** [comment]
Hello, 
I think this is due to the python3.7 upgrade, you need to reinstall python-ewmh.

**Comment by sispus** [comment]
yes, it solves the issue. thanks :)
