### ISSUE TITLE
Ran out of input

### ISSUE THREAD

**Issue by matthelosh** [j4321/MyNotes#6]
Traceback (most recent call last):
  File "/usr/bin/mynotes", line 52, in <module>
    app = App()
  File "/usr/lib/python3.6/site-packages/mynoteslib/app.py", line 116, in __init__
    note_data = dp.load()
EOFError: Ran out of input

**Comment by j4321** [comment]
I think the note data got corrupted (but I have no clue how). Deleting `~/.mynotes/notes` should solve the issue but all the notes will be lost. However, you might be able to retrieve some of them with the backups  `~/.mynotes/notes.backup#` (the largest number is the most recent one). 

Did something unexpected/unusual happen the last time your ran mynotes before getting this error message? (bug, force quit, computer crash, ...). I tried to kill mynotes, but it did not cause any data corruption.

**Comment by matthelosh** [comment]
Nothing happened before i got this error. I just updated my machine, and it stopped due to the connection.
After i rebooted i got this error.\n
But, thanks for your suggestion. It solves my error. I got it running well now.
